### PR TITLE
Add support to &&, || and ; bash operators

### PR DESCRIPTION
**Pull request by tmarti2**
This PR add the support to 3 new operators : 
- `&&` : `A &&. B` , lazy AND opperator, run B only if A exit with 0
- `||` : `A ||. B`, lazy OR operator, run B only if A do not exit with 0
- `;` : `A ->. B` sequence operator, run A, then run B regardless of A exit status

With small tests for `&&.` and `||.`.

Beware, the relative precedence of these operators is not the same as in Bash. You might need to use parenthesis instead.

### CODE REVIEW

**Comment by charlesetc** [comment]
Thanks these are great to have!

I moved the infix operators into an `Infix` module to make them more opt-in, which lets us choose the names `&&` and `||` with less worry. I think these are better mostly because the precedence matches bash's so we don't have to warn about the precedence being different than what one might expect. What do you think?

Thanks again!

**Comment by tmarti2** [comment]
Precedences for sequence operator seems wrong.
```ocaml
echo "test" |. process "true" [] ->. cat "-" |> print;
```
is evaluated as 
```ocaml
echo "test" |. (process "true" [] ->. cat "-") |> print;
```
and outputs `test`, but 
```bash
echo "test" | true && cat`
```
is evaluated as 
```bash
(echo "test" | true) && cat`
```
and here cat is waiting for input on stdin.

**Comment by tmarti2** [comment]
Since making operators with Ocaml seems a bit.. complicated, we can say that precedence doesn't match bash one, and tell people to use parenthesis unless they know what they're doing.

With you solution `&&` and `||` are right associative for me, it would be better if they were left associative to at least match bash associativity and avoid more parenthesis.

**Comment by tmarti2** [comment]
I think this is the best compromise for Infix operators. They are consistent with `->.`, and left associative like bash operators.
Regarding precedence for Pipe/Sequence, I don't think we can simply handle this, except by changing all operators to match Ocaml operators precedence (https://ocaml.org/api/Ocaml_operators.html). Keeping it like this and using parenthesis is enough. I added few tests which output the same result than bash.

If you are fine with it, I now feel this can be merged.

**Comment by charlesetc** [comment]
Ah I think I misinterpreted your original "Beware" warning and thought I was fixing the associativity to match bash's but I was in fact mistaken and it was already good! Am I correct that the only thing that differs from bash is that `->.` binds more tightly than pipe? I think that's fine, though I'll add a comment in the mli to warn people. I'll merge now, adding comments later if I'm wrong and there are more gotchas. Thanks for putting thought into this!

**Comment by tmarti2** [comment]
Yeah my bad for this. And I was not sure about pipe precedence compared to &&/|| too, I did not find clear informations about it. Thanks !

**Comment by charlesetc** [comment]
Oh no worries at all — the PR is great! ([This](https://ocaml.org/api/Ocaml_operators.html) has been my reference for operator precedence.) Anyways 🎉

**Pull request merged**
